server:
  port: ${PORT:8080}

spring:
  application:
    name: stock-tracker-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:stock;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s

app:
  cors:
    allowed-origins: "http://localhost:3000"
  markets:
    iex-token: "demo"
    alpha-vantage-key: "demo"
    finnhub-api-key: d2b6gkhr01qrj4ikk4k0d2b6gkhr01qrj4ikk4kg
    twelvedata-api-key: 4df5a0b518374ee19bd96127fda3f949

logging:
  level:
    reactor.netty.http.client: WARN
    org.springframework.web.reactive.function.client.ExchangeFunctions: WARN
